### ISSUE TITLE
clarify sponsors

### ISSUE THREAD

**Issue by geografa** [maptime/portland#24]
Let's clean up sponsor sidebar on meetup:
- Esri provides pizza and refreshments for attendees
- Mapbox covers the costs of our Meetup page and event space at WeWork (link)

(CartoDB is no longer involved)

/cc @mannylopez @mattsayler

**Comment by mattsayler** [comment]
Done, but unfortunately can't do links in the description.

**Comment by geografa** [comment]
:+1: thanks @mattsayler
