### ISSUE TITLE
February Checklist

### ISSUE THREAD

**Issue by mannylopez** [maptime/portland#26]
- [x] Choose date
- [x] Secure space
- [x] Secure topic
- [x] Secure speaker
- [x] Meetup
- [x] Calagator
- [x] maptime.io blog post
- [x] Tweet out event info

@geografa @mattsayler

**Comment by mannylopez** [comment]
Had the idea of having someone knowledgeable in Tableau present. We can cross-promote with their Meetup group as well. 

http://www.meetup.com/Portland-Tableau-User-Group/

This is the message I sent them via Meetup

```
Hi! I help run the MaptimePDX meetup here in town and are looking for a speaker to talk a bit about Tableau + maps. Would anyone be interested in talking more about this? Or, do you have any leads I can follow up with?

MaptimePDX is a beginner-focused, very hands-on meetup where we introduce people to maps and mapping technologies.

http://www.meetup.com/MaptimePDX/

People are extremely excited about data, analysis and visualization and would love to learn more about Tableau/how to visualize their data on a map.

I'm happy to grab a cup of coffee or beer to answer any questions that you may have! Let me know!

Best,
Manny
```

**Comment by mannylopez** [comment]
Got a response from Wil at the PDX Tableua User group this morning:

> Hi Manny,  
> What great timing! Our next meeting (Feb. 23rd, 5:30 to 7:30) will be about mapping with Tableau. 
> Would it make sense to invite your members to that meeting? How many MaptimePDX members do you think would attend? I will also reach out to the presenters about presenting at the MaptimePDX group. What is the best way for them to contact you?  
> Wil

**Comment by mannylopez** [comment]
My response

> Hi Wil,  
> Thanks for the reply!  
> Our attendance varies anywhere from 20-40 people on a given meetup, depending on the topic that we present.  I would love to talk more about having one of your presenters speaking at one of our events or MaptimePDX and the PDX Tableau User group teaming up to co-host this event.  
> I am at xxx-xxx-xxxx or xxx@gmail.com. Either works for me.  
> How amenable are you to co-hosting this meetup? We could potentially host it at our office space at WeWork (220 NW 8th Ave, Portland, OR 97209), which holds up to 60 people, and have Esri sponsor pizza for the event.  Where do you folks host your meetup and about how many attendees do you average?  
> Best, Manny

**Comment by mannylopez** [comment]
- Just emailed Piper asking for WeWork venue availability
- Emailed Amy for pizza request

**Comment by mannylopez** [comment]
[blog post](http://maptime.io/portland/)
[meetup invite](http://www.meetup.com/MaptimePDX/events/228827801/)
[calagator](http://calagator.org/events/1250469821)

**Comment by mannylopez** [comment]
@geografa can you tweet the following please?

Want to learn how to visualize your data on a map? Come to our next meetup on 2/23 at 6pm to learn about mapping with @tableau! RSVP http://www.meetup.com/MaptimePDX/events/228827801/

photo to use: https://cloud.githubusercontent.com/assets/3945073/13091461/3aa264fc-d4b0-11e5-9ee3-7b600fe29228.jpg

**Comment by geografa** [comment]
https://twitter.com/MaptimePDX/status/699749987375124480

**Comment by mannylopez** [comment]
:+1:

**Comment by mannylopez** [comment]
To Do
- [ ] Set up slides with sponsor info
- [ ] wifi info
- [ ] bathroom info
- [ ] Tableau and Mapbox download info
- [ ] Tableau User group mission
- [ ] WeWork word
- [ ] Maptime mission
- [ ] Presenter info
- [ ] Pints info?

**Comment by geografa** [comment]
this happened!
