### ISSUE TITLE
RSVP js broken

### ISSUE THREAD

**Issue by mannylopez** [maptime/portland#27]
The "Next MaptimePDX" div on the right side of the page is broken. 

Posts are only showing up production if the date in the file name is in the past. If the name of the file has a date in the future, the post will not appear in production, although it does appear in my local jekyll build.

I think the code is here:
https://github.com/maptime/portland/blob/gh-pages/_layouts/default.html#L83

@geografa @mattsayler

**Comment by geografa** [comment]
fixed in _config.yml https://github.com/maptime/msp/issues/11#issuecomment-194650646
