### ISSUE TITLE
Prep For Aug 05, 2015 06:00PM Meeting

### ISSUE THREAD

**Issue by mattsayler** [maptime/portland#9]
To-Do:
- Email Esri PDX to secure space
  - [ ] Email sent
  - [ ] Space secured
- [ ] Determine tutorial/presenter
- [ ] Create Calagator entry
- [x] Create Eventbrite entry
- [ ] Create Google Group entry

attn: @mattsayler @geografa @mannylopez

**Comment by geografa** [comment]
I like the idea of another Q&A/ ask the experts panel or something like that. What was the other idea?

**Comment by geografa** [comment]
Also, I can run through how to do a buildings import in JOSM since I _finally_ got through that.

**Comment by mattsayler** [comment]
Q&A/AtE would be good. Seems like @mannylopez had something in mind or lined up already, but I don't remember.

I kind of feel like the JOSM buildings import would be better for a PDX-OSGeo crowd than a Maptime crowd.
